### ISSUE TITLE
怎么加入开发团队呀？

### ISSUE THREAD

**Issue by timeswind** [auto-xxqg/auto-xxqg#82]
有兴趣一起参与这个项目，麻烦大佬看到后联系我一下tswymt@gmail.com github.com/timeswind

**Comment by Gingmzmzx** [comment]
已经邀请你了，还需要你加一下开发部的tg群，在tg群先加我联系人，然后我拉你

**Comment by timeswind** [comment]
@Gingmzmzx 你在TG群里的名字是什么？

**Comment by Gingmzmzx** [comment]
我就叫gingmzmzx
